// <auto-generated />
namespace Sales.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomersAddAgeDefaultValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomersAddAgeDefaultValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201703041140176_CustomersAddAgeDefaultValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
